apiVersion: v1
kind: Service
metadata:
  name: consumer
  namespace: baseline
  labels:
    app: consumer
    strategy: hpa
spec:
  type: ClusterIP
  selector:
    app: consumer
    strategy: hpa
  ports:
    - name: http
      port: 8080
      targetPort: 8080
