apiVersion: v1
kind: Namespace
metadata:
  name: rabbitmq
  labels:
    app.kubernetes.io/part-of: cs5296-experiment
---
apiVersion: v1
kind: Namespace
metadata:
  name: baseline
  labels:
    app.kubernetes.io/part-of: cs5296-experiment
    experiment.cs5296/group: baseline
---
apiVersion: v1
kind: Namespace
metadata:
  name: keda
  labels:
    app.kubernetes.io/part-of: cs5296-experiment
    experiment.cs5296/group: event-driven-keda
